spring.application.name=server

logging.pattern.console=%d{HH:mm:ss} | [%thread] %-5level %logger{36} - %msg%n

logging.level.org.hibernate=warn

spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true

logging.level.org.hibernate.orm.connections.pooling=error
spring.jpa.hibernate.ddl-auto=none
logging.level.org.hibernate.SQL=off
logging.level.org.hibernate.type.descriptor.sql=off

logging.level.org.springframework.jdbc=warn

logging.level.com.zaxxer.hikari=warn

spring.profiles.active=${ACTIVE_PROFILE:dev}
